steps:
- name: "node"
  entrypoint: "npm"
  args: ["install"]
- name: "node"
  entrypoint: "npm"
  args: ["--prefix", "frontend", "ci"]
- name: "node"
  entrypoint: "npm"
  args: ["--prefix", "frontend", "run", "build"]
- name: "node"
  entrypoint: "npm"
  args: ["--prefix", "backend", "ci"]
- name: "node"
  entrypoint: "npm"
  args: ["--prefix", "backend", "test"]
options:
  logging: CLOUD_LOGGING_ONLY